### ISSUE TITLE
Not compatible with the version of your running IDE (PhpStorm 2022.2)

### ISSUE THREAD

**Issue by Tseka85** [vyach-vasiliev/idea_deploy_for_commits#1]
Hello, can you update?

**Comment by vyach-vasiliev** [comment]
@Tseka85 Thank you for report!

Now released a new version compatible with [2022.* version](../releases/tag/v2.0-2022).
_It is currently being reviewed by [Jetbrains Marketplace](https://plugins.jetbrains.com/plugin/14091-deploy-for-commits/versions/stable/218891)._

Please check and let me know if this issue is resolved.

**Comment by Tseka85** [comment]
Ok, thank you !
