### ISSUE TITLE
Support for PHPStorm 242.*+

### ISSUE THREAD

**Issue by YellowFoxNK** [vyach-vasiliev/idea_deploy_for_commits#3]
Plugin is actually not compatible with the newest phpstorm version. Coul you please create a plugin without a PuntilApp restriction?

**Comment by vyach-vasiliev** [comment]
Thanks for your response!
Please check the [latest version](https://plugins.jetbrains.com/plugin/14091-deploy-for-commits), there I removed the limitation of the final version, but raised the limitation of the initial one due to the transition from [org.jetbrains.intellij](https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html) to [org.jetbrains.intellij.platform](https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin.html).

**Comment by vyach-vasiliev** [comment]
> Plugin is actually not compatible with the newest phpstorm version. Coul you please create a plugin without a PuntilApp restriction?

Thanks for your response!
Please check the [latest version](https://plugins.jetbrains.com/plugin/14091-deploy-for-commits), there I removed the limitation of the final version, but raised the limitation of the initial one due to the transition from [org.jetbrains.intellij](https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html) to [org.jetbrains.intellij.platform](https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin.html).
